services:
  api:
    image: registry.bmw-nsk.ru/bmw-nsk/api@${API_DIGEST}
    container_name: 'bmw-nsk-api-${SLUG}'
    restart: unless-stopped
    networks: [traefik]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    labels:
      org.label-schema.group: 'bmw-nsk-dynamic'
      traefik.enable: true
      traefik.http.routers.bmw-nsk-api-${SLUG}.tls: true
      traefik.http.routers.bmw-nsk-api-${SLUG}.tls.certresolver: 'letsencrypt'
      traefik.http.routers.bmw-nsk-api-${SLUG}.rule: 'Host(`${API_URL}`)'
      traefik.http.routers.bmw-nsk-api-${SLUG}.service: 'bmw-nsk-api-${SLUG}'
      traefik.http.services.bmw-nsk-api-${SLUG}.loadbalancer.server.port: 5000

networks:
  traefik:
    external: true
