services:
  postgres:
    image: postgres:15.1-alpine3.17
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'nc', '-z', 'localhost', '5432' ]
      interval: 5s
      timeout: 15s
      retries: 1
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
