name: 'Deploy preview'

on:
  workflow_call:

jobs:
  build-push-api:
    name: 'Prepare "API" image'
    uses: ./.github/workflows/_build-push-dockerfile.yml
    with:
      image-name: bmw-nsk/api
      image-tag: pr-${{ github.event.pull_request.number }}
      dockerfile: apps/api/Dockerfile
    secrets: inherit

  update-states-repository:
    name: 'Notify "bmw-nsk-states"'
    needs: [ build-push-api ]
    runs-on: self-hosted
    steps:
      - name: 'Prepare $SLUG variable'
        run: echo "SLUG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: 'Prepare environment variables'
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          
          echo "API_IMAGE=${{ needs.build-push-api.outputs.image }}" >> $GITHUB_ENV
          echo "API_URL=api.$SLUG.bmw-nsk.ru" >> $GITHUB_ENV
          echo "NODE_ENV=dynamic" >> $GITHUB_ENV
          
          echo "ADMIN_URL=admin.$SLUG.bmw-nsk.ru" >> $GITHUB_ENV
          echo "ADMIN_S3_URL=https://admin-dist.s3.bmw-nsk.ru/$SLUG/" >> $GITHUB_ENV

      - name: 'Checkout "bmw-nsk-states"'
        uses: actions/checkout@v3
        with:
          repository: digital-blade/bmw-nsk-states
          token: ${{ secrets.STATES_REPOSITORY_TOKEN }}

      - name: 'Render docker-compose.yml'
        run: |
          envsubst < .template/docker-compose.yml > docker-compose.yml
          cat docker-compose.yml