name: 'Tests'

on:
  workflow_call:
    inputs:
      base-sha:
        type: string
        required: true

env:
  TURBO_API: ${{ vars.TURBO_API }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  code-quality:
    name: 'Code quality'
    runs-on: [self-hosted]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 15

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v2

      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 'Install dependencies'
        run: pnpm install --frozen-lockfile

      - name: 'Build libraries'
        run: pnpm turbo run --filter=./packages/* build

      - name: 'Test dependencies'
        run: pnpm test:deps

      - name: 'Test Prettier'
        run: pnpm test:format

      - name: 'Test ESLint'
        continue-on-error: true
        run: pnpm turbo run --filter=[${{ inputs.base-sha }}] test:lint-report

      - name: 'Merge ESLint report'
        run: find apps packages -name 'eslint-report.json' -exec cat {} + | jq -s '[.[]]|flatten' > eslint-report.json

      - name: 'Annotate ESLint results'
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: eslint-report.json
