name: 'Cleanup pull request'
run-name: 'Cleanup pull request: "${{ github.head_ref }}" by "${{ github.actor }}"'

on:
  pull_request:
    types: [ closed ]

jobs:
  cleanup:
    name: 'Cleanup'
    runs-on: [ self-hosted ]
    steps:
      - name: "Wait Deployment complete"
        uses: lewagon/wait-on-check-action@v1.2.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          running-workflow-name: 'Deploy'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: "Slugify branch"
        uses: rlespinasse/slugify-value@v1.x
        with:
          key: BRANCH_NAME
          value: ${{ github.head_ref }}

      - name: "Checkout states repository"
        uses: actions/checkout@v3
        with:
          repository: digital-blade/bmw-club-states
          ref: ${{ github.head_ref }}
          token: ${{ secrets.STATES_REPOSITORY_TOKEN }}

      - name: "Remove states branch"
        run: git push origin --delete ${{ github.head_ref }}

      # It deletes environments, but throws an error
      # https://github.com/bobheadxi/deployments/issues/135
      - name: "Delete environment"
        uses: bobheadxi/deployments@v1
        continue-on-error: true
        with:
          step: delete-env
          token: ${{ secrets.MONOREPO_DEPLOY_TOKEN }}
          env: ${{ env.BRANCH_NAME_SLUG_URL }}
          desc: Environment was pruned
