name: 'Cleanup pull request'
run-name: 'Cleanup pull request: "${{ github.head_ref }}" by "${{ github.actor }}"'

on:
  pull_request:
    types: [ closed ]

concurrency:
  group: deploy-${{ github.head_ref }}

permissions:
  deployments: write

jobs:
  cleanup:
    name: 'Cleanup'
    runs-on: [ self-hosted ]
    steps:
      - name: "Slugify branch"
        uses: rlespinasse/slugify-value@v1.x
        with:
          key: BRANCH_NAME
          value: ${{ github.head_ref }}

      - name: "Checkout states repository"
        uses: actions/checkout@v3
        with:
          repository: digital-blade/bmw-club-states
          ref: ${{ github.head_ref }}
          token: ${{ secrets.STATES_REPOSITORY_TOKEN }}

      - name: "Remove states branch"
        run: git push origin --delete ${{ github.head_ref }}

      - name: "Delete environment"
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.BRANCH_NAME_SLUG_URL }}
          desc: Environment was pruned
