name: 'Cleanup pull request'
run-name: 'Cleanup pull request: "${{ github.head_ref }}" by "${{ github.actor }}"'

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:
  cleanup-preview:
    name: 'Cleanup preview'
    runs-on: self-hosted
    steps:
      - name: 'Debug'
        run: echo "Cleanup here"
