name: 'Pull request'
run-name: 'Pull request: "${{ github.head_ref }}" by "${{ github.actor }}"'

on:
  pull_request:
    branches: [ develop ]

jobs:
#  tests:
#    name: 'Tests'
#    concurrency:
#      group: tests-${{ github.head_ref }}
#      cancel-in-progress: true
#    uses: ./.github/workflows/_tests.yml
#    secrets: inherit

  deploy-preview:
    name: 'Deploy preview'
    concurrency:
      group: deploy-preview-${{ github.head_ref }}
      cancel-in-progress: true
    uses: ./.github/workflows/_deploy-preview.yml
    secrets: inherit
